apiVersion: v1
kind: Secret
metadata:
    name: secrets
type: Opaque
data:
    grafana_admin_user: dXNlcjE= # echo -n "user1" | base64
    grafana_admin_password: cGFzc3dvcmQx # echo -n "password1" | base64